### ISSUE TITLE
Doesn`t work :(

### ISSUE THREAD

**Issue by abada** [hansemannn/Ti.GoogleMaps#1]
Ti SDK 5.1.0.v20151104190037

**Comment by hansemannn** [comment]
Hey @abada, can you please provide more infos? And make sure you following the guide to include the `GoogleMaps.bundle` inside `platform/iphone`.

**Comment by abada** [comment]
Hi  @hansemannn,

Where can i found `oogleMaps.bundle` ?

**Comment by abada** [comment]
It works , thank you :)
