### ISSUE TITLE
Build failed when compiling module

### ISSUE THREAD

**Issue by burgons** [hansemannn/ti.googlemaps#11]
Hi Hans, any idea why the most recent code failed to build?
There are three missing files listed at the bottom of the output below:

- file: /Volumes/usr/lib/libc++.1.dylib
- file: /Volumes/usr/lib/libicucore.A.dylib
- file: /Volumes/usr/lib/libz.1.dylib

Here's the last few lines of the console log:

```
Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a normal arm64
    cd "/Volumes/Documents HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone"
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only arm64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/Release-iphoneos -filelist /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/TiGooglemaps.LinkFileList /Volumes/usr/lib/libc++.1.dylib /Volumes/usr/lib/libicucore.A.dylib /Volumes/usr/lib/libz.1.dylib -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreText -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework ImageIO -framework Foundation -framework GoogleMaps -o /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libc++.1.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libicucore.A.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libz.1.dylib (No such file or directory)

Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a normal armv7
    cd "/Volumes/Documents HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone"
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only armv7 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/Release-iphoneos -filelist /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/TiGooglemaps.LinkFileList /Volumes/usr/lib/libc++.1.dylib /Volumes/usr/lib/libicucore.A.dylib /Volumes/usr/lib/libz.1.dylib -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreText -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework ImageIO -framework Foundation -framework GoogleMaps -o /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libc++.1.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libicucore.A.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libz.1.dylib (No such file or directory)

** BUILD FAILED **

The following build commands failed:
	Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a normal arm64
	Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a normal armv7
(2 failures)
xcodebuild failed
```

**Comment by hansemannn** [comment]
Did that work before? If so, which version / commit broke it for you? Also, make sure you have the "Xcode command line tools" which include those libraries.

**Comment by burgons** [comment]
Hi Hans

Reinstalled "Xcode command line tools" and get the error below.

Build settings from command line:
    SDKROOT = iphoneos9.2

=== BUILD TARGET ti.googlemaps OF PROJECT ti.googlemaps WITH CONFIGURATION Release ===

Check dependencies

Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a normal arm64
    cd "/Volumes/Documents HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone"
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only arm64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/Release-iphoneos -filelist /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/TiGooglemaps.LinkFileList /Volumes/usr/lib/libc++.1.dylib /Volumes/usr/lib/libicucore.A.dylib /Volumes/usr/lib/libz.1.dylib -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreText -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework ImageIO -framework Foundation -framework GoogleMaps -o /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libc++.1.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libicucore.A.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libz.1.dylib (No such file or directory)

Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a normal armv7
    cd "/Volumes/Documents HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone"
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/git/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only armv7 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/Release-iphoneos -filelist /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/TiGooglemaps.LinkFileList /Volumes/usr/lib/libc++.1.dylib /Volumes/usr/lib/libicucore.A.dylib /Volumes/usr/lib/libz.1.dylib -framework Accelerate -framework AVFoundation -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreText -framework GLKit -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework ImageIO -framework Foundation -framework GoogleMaps -o /Volumes/Documents\ HD/simon/Desktop/_googleMapModule/Ti.GoogleMaps-master/iphone/build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libc++.1.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libicucore.A.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Volumes/usr/lib/libz.1.dylib (No such file or directory)

** BUILD FAILED **


The following build commands failed:
	Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/arm64/libTiGooglemaps.a normal arm64
	Libtool build/ti.googlemaps.build/Release-iphoneos/ti.googlemaps.build/Objects-normal/armv7/libTiGooglemaps.a normal armv7
(2 failures)
xcodebuild failed

**Comment by hansemannn** [comment]
Interesting..`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool` can be found on my machine. Will need to check some more details on those libraries. The main problem is, that we link dynamic libraries to a static library. Need to find a better way though.

**Comment by hansemannn** [comment]
Hey @burgons, unfortunately I have been unable to reproduce during my work on the latest 2.2.0 release. Please check that version out running Xcode 7 and Xcode Developer Tools installed. If the issue is still existing, let me know!
