### ISSUE TITLE
Small typo in ReadMe & Workaround to 5.2.0

### ISSUE THREAD

**Issue by yozef** [hansemannn/Ti.GoogleMaps#14]
> If you use Ti.SDK < 5.2.0.GA you can use the module just like before, if you use Ti.SDK 5.2.0.GA you can already use the latest module version (1.1.0) and upgrade to 5.2.1.GA asap.

I think you meant "the latest module version (**2**.1.0)". 

On another note...

> you need to copy the GoogleMaps.bundle located in iphone/platform/ios/ manually inside the generated Xcode project.

I assume it's in the Generated Xcode Project of the App compiled with Titanium (inside `build/platform/myProj.xcodeproj`). I tried adding it to the Xcode's Poject LinkedFrameworks and Libraries, however, everytime I run the app again from Titanium, that gets updated without the bundle. Maybe I'm adding it wrong to the built XcodeProject?

**Comment by hansemannn** [comment]
It's critical...and may really need to be necessary to be fixes along with 5.2.1.GA. Does copying it to "platform/ios" or "platform/iphone" work?

**Comment by yozef** [comment]
I created `platform/ios' in the Titanium project and added the bundle there, and ran, got the black screen. I tried again with `platform/iphone` and got the same issue.

**Comment by hansemannn** [comment]
That's bad. Corrected the typo and the readme, but you'll probably need to wait for the 5.2.1.GA or patch your SDK until then. Unfortunately, I can not do much more on the module-side, but will push forward the related ticket. Thanks!

**Comment by yozef** [comment]
No problem at all @hansemannn :)
It's not urgent, it can wait for 5.1.2.GA
