### ISSUE TITLE
Submit to App Store errors

### ISSUE THREAD

**Issue by burgons** [hansemannn/ti.googlemaps#19]
Hi

Trying to submit an app to the App Store and getting the following errors. Any ideas why?

![screen shot 2016-03-10 at 23 07 31](https://cloud.githubusercontent.com/assets/1049641/13689156/df01e9ca-e71e-11e5-97f5-5a33c67bbe22.png)

![screen shot 2016-03-10 at 23 07 44](https://cloud.githubusercontent.com/assets/1049641/13689159/e3f00d7c-e71e-11e5-92ec-8a83f3683eed.png)

![screen shot 2016-03-10 at 23 07 51](https://cloud.githubusercontent.com/assets/1049641/13689164/ec5910da-e71e-11e5-8953-76c62de711c0.png)

![screen shot 2016-03-10 at 23 08 00](https://cloud.githubusercontent.com/assets/1049641/13689170/f2f35ed2-e71e-11e5-9d6c-d29029a8915f.png)

**Comment by hansemannn** [comment]
Workaround: Right click on the "GoogleMaps.bundle" and "Show contents", navigate to the bundle's Info.plist, clean it up and try it again. Will figure out tomorrow, why exactly those values are there. Thanks!

**Comment by burgons** [comment]
Thanks Hans

I’ll give that a go.

Cheers

**Comment by burgons** [comment]
Followed your workaround. Built with TiSDK 5.1.0GA - but still fails to pass upload validation.

**Comment by burgons** [comment]
Do you know where I can locate the latest bundle?

**Comment by burgons** [comment]
OK - I grabbed a new version of the Google iOS SDK, located the GoogleMaps.bundle and copied it to the Ti.Googlemaps module. Rebuilt and submitted successfully to the App Store this morning.
Hope that helps...

**Comment by hansemannn** [comment]
Thanks. I did the same, interesting your's worked. Can you submit a PR with the new bundle? Thanks!

**Comment by macasfaj** [comment]
Please. I need to upload today to Apple Store. Can you release a new version 2.1.1, please? You'll save my life!

**Comment by burgons** [comment]
Hi Hans. Sorry I won't be able to submit a PR today.

**Comment by hansemannn** [comment]
Hi @macasfaj, just packaged a new version including the latest Google Maps iOS SDK: https://www.dropbox.com/s/rvoptof7gy8xi7y/ti.googlemaps-iphone-2.1.1.zip?dl=0

I will release it officially if all works for you.

**Comment by macasfaj** [comment]
Thanks!!! I'll check it!!

Enviado desde mi iPhone

**Comment by macasfaj** [comment]
@hansemannn It is fine! Publish!! :) Thanks!!!

**Comment by hansemannn** [comment]
New version 2.1.1 release [here](https://github.com/hansemannn/ti.googlemaps/releases/tag/v2.1.1). Thanks for reporting!
