### ISSUE TITLE
Marker dragend not working

### ISSUE THREAD

**Issue by abada** [hansemannn/Ti.GoogleMaps#2]
var marker = maps.createMarker({
    latitude : latitude,
    longitude : longitude,
    title : "Appcelerator, Inc",
     snippet : "1732 N. 1st Street, San Jose",
     icon: "/images/marker.png", // Default: null
    tappable: true, // Default: true
    draggable: true, // Default: false
    flat: false 
    });

    mapView.addMarker(marker);

Marker can not move

**Comment by hansemannn** [comment]
Hi @abada , I just checked it and everything works just as expected using the provided arguments. I also updated the latest version to improve the example and change the draggable default value to false, please check it out.

**Comment by abada** [comment]
Hi @hansemannn ,

Thank you for your reply , i will check it .

I noticed the module have many args but doesn`t have Doc .

Thank you again.

**Comment by hansemannn** [comment]
I rely very close on the offical [Google Maps iOS SDK API](https://developers.google.com/maps/documentation/ios-sdk/), an official docs page will take a bit, since it is a project besides my work.

**Comment by abada** [comment]
It works :+1:  thank you
