### ISSUE TITLE
Animate to zoom

### ISSUE THREAD

**Issue by twmfox** [hansemannn/ti.googlemaps#21]
Hi Hans,

I've actually encounter an issue with the **mapView.animateToZoom(5)** function.

Actually i've tried to use it in differents ways, by triggering it in a click listener, after loading a view, but none of my tries worked out.

I just wanted to know if this issue has been solved in your latest version ?
I'm actually using the 2.1.1 version of your module with the latest stable 5.2.0 SDK

Thanks in advance for your reply.

**Comment by hansemannn** [comment]
Hey @twmfox, will check the issue for the next patch release! Pretty sure I execute it on the wrong thread. Will update this issue as soon as it's fixed!

**Comment by hansemannn** [comment]
Hey there! Just checked the [Google Maps iOS docs](https://developers.google.com/maps/documentation/ios-sdk/views?hl=en#zoom) and it says it depends on the current location, zoom level and map type. Can you check the issue with a different map type? Maybe that's it. The code can't be wrong, I'm 90 % sure.
