### ISSUE TITLE
ti.googlemaps adds ~150 MB to ipa

### ISSUE THREAD

**Issue by yozef** [hansemannn/ti.googlemaps#25]
When running the App with ti.googlemaps, the size of the App comes up to over 150 mb. I am pretty sure it is the size of the GoogleMaps framework that is increasing the size. I am wondering if there is a way we can avoid such a huge size. The official GoogleMaps App for iOS is 48 mb.

**Comment by hansemannn** [comment]
Is the .ipa also 150 MB or just the project itself? The framework should be compiled conditionally, that needs some investigation.

**Comment by yozef** [comment]
Hi @hansemannn, yes the .ipa comes up to over 150 Mb

**Comment by hansemannn** [comment]
Hey @yozef, just tested the issue and compiled an app using the latest 2.2.0 version (from today). The app size is 9.7 MB. Maybe I placed the framework incorrectly in one version, but the latest version should definitely work well. 
<img width="578" alt="bildschirmfoto 2016-04-10 um 23 14 11" src="https://cloud.githubusercontent.com/assets/10667698/14413163/207194f8-ff72-11e5-846d-7438dfe96bc3.png">
