### ISSUE TITLE
[ERROR] Module de.hansknoechel.googlemaps version 2.2.0 is missing library file

### ISSUE THREAD

**Issue by abada** [hansemannn/ti.googlemaps#26]
[ERROR] Module de.hansknoechel.googlemaps version 2.2.0 is missing library file: ~/modules/iphone/de.hansknoechel.googlemaps/2.2.0/libde.hansknoechel.googlemaps.a

**Comment by hansemannn** [comment]
What? The module was renamed to `ti.googlemaps` versions ago. Please check your env first
