### ISSUE TITLE
How to see the Compass in map? can do?

### ISSUE THREAD

**Issue by gabrielGallardo** [hansemannn/ti.googlemaps#29]

**Comment by hansemannn** [comment]
You can use the `myLocationEnabled` for this.

**Comment by gabrielGallardo** [comment]
How to use this property?, i try this:

var mapa = maps.createView({
    mapType: maps.MAP_TYPE_NORMAL,
    myLocationEnabled: true
});

But nothing.

**Comment by gabrielGallardo** [comment]
Sorry, this works fine, however I would like to see the compass that appears on google maps on the top right, is it possible?

**Comment by hansemannn** [comment]
Nope, that's not exposed by the Google Maps SDK.

**Comment by gabrielGallardo** [comment]
Ok, thanks.

**Comment by yozef** [comment]
Actually there is: 
https://developers.google.com/maps/documentation/ios-sdk/controls#compass
~~~
GMSMapView *mapView_;
mapView_.settings.compassButton = YES;
~~~

**Comment by yozef** [comment]
There is a PR for compassButton and more...

**Comment by hansemannn** [comment]
Reopening! I read the issue too fast. Of course `myLocationEnabled` != `compassEnabled`. @yozef do you want to add it to your existing PR?
