### ISSUE TITLE
There is no GoogleMaps.bundle in the downloaded module - only GoogleMaps.framework

### ISSUE THREAD

**Issue by Mobilizr** [hansemannn/Ti.GoogleMaps#3]
First of all thanks so much for sharing your work on this module.

The README for this project says...

> NOTE: For now, you need to copy the GoogleMaps.bundle from <PROJECT_ROOT>/modules/de.hansknoechel.googlemaps/<VERSION>/platform to <PROJECT_ROOT>/platform/iphone to make the module run. This only needs to be done the first time you install the module. We are working to get this done automatically.

However inside the <PROJECT_ROOT>/modules/de.hansknoechel.googlemaps/<VERSION>/platform directory there is only a file called GoogleMaps.framework.

Is this the file that needs to be moved? I would have assumed so, but then when I build the project I get the following error:

> [ERROR] : message = "GoogleMaps.bundle requires Google Maps SDK for iOS to be part of your target under 'Copy Bundle Resources'";

Any tips on how to solve this problem? I believe I have followed the instructions provided correctly, but maybe I have missed something...

**Comment by Mobilizr** [comment]
I managed to locate the GoogleMaps.bundle file inside the "Source code (zip)" download.

**Comment by hansemannn** [comment]
Hi @Mobilizr, thank you! I verified the issue and (at least in the latest version) the file exists in the packaged module. Hopefully you are all set now.

**Comment by Mobilizr** [comment]
Sweet - thanks @hansemannn :)
