### ISSUE TITLE
mapView.removeAnnotation(marker);

### ISSUE THREAD

**Issue by adelsamy** [hansemannn/ti.googlemaps#32]
Hi Dear,
please why function removeAnnotation(marker); is not working get me error Invalid type passed

**Comment by twmfox** [comment]
Hi @adelsamy could share a code sample ? I'm actually using removeAnnotation and I haven't got any problem with it.

**Comment by hansemannn** [comment]
Hey @adelsamy, make sure you remove a `Annotation` proxy when using `removeAnnotation`, not a `Marker` proxy (which is deprecated in 2.2.0).

**Comment by adelsamy** [comment]
yes now working with  me Thank you @twmfox  @hansemannn
