### ISSUE TITLE
App crashes after using v2.3.0

### ISSUE THREAD

**Issue by abada** [hansemannn/ti.googlemaps#35]
```
[ERROR] An error occurred during build after 5m 32s 21ms
[ERROR] Detected multiple crashes:
[ERROR]   /Users/abdellatifhenno/Library/Logs/DiagnosticReports/proj_2016-04-11-183816_abada-2.crash
[ERROR]   /Users/abdellatifhenno/Library/Logs/DiagnosticReports/proj_2016-04-25-012722_abada-2.crash
[ERROR]   /Users/abdellatifhenno/Library/Logs/DiagnosticReports/proj_2016-04-25-013343_abada-2.crash
[ERROR] Note: these crashes may or may not be related to running your app.

```

`<sdk-version>5.2.2.GA</sdk-version>`

**Comment by yozef** [comment]
Hi @abada Are you using the one module distributed here: [https://github.com/hansemannn/Ti.GoogleMaps/releases](https://github.com/hansemannn/Ti.GoogleMaps/releases)

**Comment by hansemannn** [comment]
2.3.0 should be stable. Make sure you use the correct API and migrated your markers to annotations, mapview to view etc. Although it should still work, using latest technologies is advised. Check the readme for the API-usage.

**Comment by abada** [comment]
@yozef  Yes i did

@hansemannn  Actually it working at first time , but then failed !

**Comment by hansemannn** [comment]
Pretty sure it's something on your side, otherwise more people would have reached out here. Please verify it's not another API that's causing it. Will keep this open anyway, maybe others experience the same over the week. Also please provide a trace-log (ti build -p ios --log-level trace).

**Comment by abada** [comment]
Ok 👍   Thanks

**Comment by abada** [comment]
It works , thank you
