### ISSUE TITLE
New Feature: Support custom popups

### ISSUE THREAD

**Issue by rborn** [hansemannn/ti.googlemaps#36]
Hi, is there any way to make a custom popup (info bubble when you tap on a marker)?
Thank you :)

**Comment by isseium** [comment]
+1

I want to know it too.

**Comment by hansemannn** [comment]
It is possible and it already, I just have an open issue where proxy-views are not attached correctly when showing them the first time. If someone wants to help, here is the current status:

```objc
-(UIView *)mapView:(GMSMapView *)mapView markerInfoWindow:(GMSMarker *)marker
{
    TiGooglemapsAnnotationProxy *proxy = [self annotationProxyFromMarker:marker];
    
    if (!proxy) {
        NSLog(@"[ERROR] Trying to create an infoWindow from an annotation that is not recognized.");
        return;
    }
    
    ENSURE_TYPE([proxy valueForKey:@"infoWindow"], TiViewProxy);
    [proxy rememberSelf];
    
    return [(TiViewProxy*)[proxy valueForKey:@"infoWindow"] view];
}
```

// cc @yozef

**Comment by rborn** [comment]
My understanding (from a paid module in the Appc Marketplace) is that you need that view created BEFORE attaching it to the map due to some weird way titanium handles the view proxies.
But I might be totally off the track 😀

**Comment by hansemannn** [comment]
After some backend work on the threading / queuing, the above seems to work fine. Please do some tests on #58 to confirm, thx!

**Comment by hansemannn** [comment]
There is a `really bad` hack that allows the usage already:
```js
    var infoWindow = Ti.UI.createView({width: 200,height: 30, backgroundColor: "#ff0"});
    infoWindow.add(Ti.UI.createLabel({text: 'Annotation ' + i}));
    var _ = Ti.UI.createImageView({width: 200,height: 30, image: infoWindow.toImage()});
        
    var annotation = maps.createAnnotation({
        latitude: getRandomInRange(37,38, 4),
        longitude: getRandomInRange(-120,-122, 4),
        infoWindow: _,
    });
```

**Comment by hansemannn** [comment]
Supported as part of #74.
