### ISSUE TITLE
Couldn't find module: tigooglemaps for architecture: x86_64

### ISSUE THREAD

**Issue by didats** [hansemannn/Ti.GoogleMaps#4]
I have checked the build, and the architecture is correct. Not sure what cause the problem.

$ xcrun lipo -info libti.googlemaps.a 
Architectures in the fat file: libti.googlemaps.a are: armv7 i386 x86_64 arm64

**Comment by hansemannn** [comment]
Hi @didats, I'm sure we can figure this out. Some things to check:
- Make you have have the latest version downloaded from the "Releases" tab
- Make sure to include the module with `var GoogleMaps = require("ti.googlemaps");`
- Make sure the `modules/iphone/ti.googlemaps` directory is inside the root of your project
- Make sure the module is selected in your project's `tiapp.xml` file

**Comment by didats** [comment]
Okay, i didn't know the module should be on the rood of the project as well. Thank you.
