### ISSUE TITLE
Custom Annotations

### ISSUE THREAD

**Issue by snehalhumne** [hansemannn/ti.googlemaps#42]
Hi, Can you please provide me the details, whether we can create the custom annotation pins in the ti.googlemaps module??

**Comment by yozef** [comment]
~~~
var annotation = maps.createAnnotation({
    latitude : 37.368122,
    longitude : -121.913653,
    title : "Appcelerator, Inc",
    image: "pin.png", // Add your custom image here
});
mapView.addAnnotation(annotation);
~~~

**Comment by snehalhumne** [comment]
yes, But in ti.map module, we can create the customView for annotations, can we do that in googlemaps also???

**Comment by yozef** [comment]
I see your point now. The Custom View is for the Bubble, not the image annotation. For what I can see, this is not possible with native Google Maps SDK, so we can't wrap it into a Appc module since it's not provided.

**Comment by hansemannn** [comment]
This was asked a few times before. Just create a view and use the built-in core-method `toImage()` to build an image from the view and pass that to the `image` property.
