### ISSUE TITLE
How duplicate pins at same locations handled by clustering?

### ISSUE THREAD

**Issue by MushoodMunir** [hansemannn/ti.googlemaps#45]
Hi,
First of all i appreciate your efforts for clustering support in iOS maps. I am currently using this in my Titanium app and it is working quite nicely even with custom images used for pins. I want to know that how duplicate entries are currently being handled in cluster. i.e If i add 2-3 pins at same Latitude,Longitude  in map. How cluster is currently handling them. It adds up only one of them or all of them to show number on cluster. And by the why i am asking about t.maps not for ti.googlemaps. Thanks

**Comment by hansemannn** [comment]
This module has no relation to "t.maps", sorry.
