### ISSUE TITLE
New version of Google Maps SDK for iOS available: 2.0.26137.0

### ISSUE THREAD

**Issue by yozef** [hansemannn/ti.googlemaps#47]
I will attempt to replace the SDK with the latest.

Current version in 2.4.0 is: Google Maps SDK for iOS version: 1.13.23885.0

**Comment by yozef** [comment]
Seems there has been changes post GoogleMaps SDK 2.0 binary has been reduced to less than 100MB to avoid exceeding GitHub's file size limit.

@hansemannn 
We might need a workaround for the two Frameworks (used to be 1 binary):
- GoogleMapsBase.framework
- GoogleMaps.framework

This will also solve our issue with github in uploading these frameworks as part of the repo.

**Comment by hansemannn** [comment]
**Very** interesting! Will checkout and try to put push it again. It would also make travis working again.

**Comment by hansemannn** [comment]
Closing for further discussion in #48, thanks!

**Comment by hansemannn** [comment]
New release: https://github.com/hansemannn/ti.googlemaps/releases/tag/v2.5.0
