### ISSUE TITLE
New Feature: Expose Camera to fit Annotation to bounds

### ISSUE THREAD

**Issue by dave101** [hansemannn/ti.googlemaps#49]
Is there any facility to fit Annotations to map bounds so they can all be displayed?

The google maps API does provide this. see fitBounds function:
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_camera_update.html#aa5b05606808272f9054c54af6830df3e

Otherwise is there is a way of manually calculating this in pure javascript?

**Comment by hansemannn** [comment]
The camera-API is not exposed, yet. I will mark it as an enhancement for a future version.

**Comment by hansemannn** [comment]
Hey @dave101, I just exposed the whole camera-updates API in https://github.com/hansemannn/ti.googlemaps/pull/58/commits/4c84f398b237c7121abcd8790d2456f31473c78d. If you want to help, write the docs and example or buy me a coffee :-)

**Comment by dave101** [comment]
Great! thanks for this @hansemannn. Looks good, hopefully get a chance soon to write up an example and docs for you. I would buy you a coffee (or beer) but I'm all the way in Australia :)

**Comment by hansemannn** [comment]
I'll ping you when I ever get there. Prepare! 🍺
