### ISSUE TITLE
indoor maps support.

### ISSUE THREAD

**Issue by MangeshVyas** [hansemannn/Ti.GoogleMaps#5]
Thanks for this great Help. Is there any way we can extend this to support Google indoor maps ?
Since its possible in Native but can we do similar with this module also ?

**Comment by hansemannn** [comment]
Hey @MangeshVyas, the official Google Maps iOS SDK docs state:

> **Indoor Maps**

> At high zoom levels, the Google Maps SDK for iOS will show floor plans for indoor spaces such as airports, shopping malls, large retail stores, and transit stations. Indoor floor plans are integrated into the default map tiles for the 'normal' map type (kGMSTypeNormal), and are automatically enabled when the user zooms in, and fade away when the map is zoomed out.

So it is enabled by default on higher zoom levels. The only thing we could do is making it possible to disable the property manually.

More infos [here](https://developers.google.com/maps/documentation/ios-sdk/map#indoor_maps).
