### ISSUE TITLE
New Feature: Map Styling

### ISSUE THREAD

**Issue by cansoysal** [hansemannn/ti.googlemaps#53]
Hi,
Do you mind to add map styling to the module? It would be a great addition.

**Comment by hansemannn** [comment]
Please specify more details regarding your feature-request.

**Comment by yozef** [comment]
I can add this (though my code dosen't package the module) :p

**Comment by cansoysal** [comment]
@hansemannn Well, There is styling feature in iOS SDK. It is possible to use json as stylebook. https://developers.google.com/maps/documentation/ios-sdk/styling and generator is here https://mapstyle.withgoogle.com/

**Comment by hansemannn** [comment]
Ok, looks easy to do. I will implement it in the next feature release.

**Comment by hansemannn** [comment]
Included in https://github.com/hansemannn/ti.googlemaps/pull/51

**Comment by andersdp** [comment]
Hi - just started working with this module. Much better than the Titanium Maps module :)

How do I use this mapStyle property? Can't figure it out.
