### ISSUE TITLE
Bug: Crash on "addAnnotation"

### ISSUE THREAD

**Issue by cansoysal** [hansemannn/ti.googlemaps#54]
Hi,
I am having difficulties adding annotation to map. AddAnnotation method is just crashing the app.
_iOS 10 + 5.5.0.GA_

**Here is the simple code to test.**

```
var maps = require("ti.googlemaps");
maps.setAPIKey(APIKEY);

var mapView = maps.createView({
    mapType: maps.MAP_TYPE_TERRAIN,
    indoorEnabled: true, // shows indoor polygons of mapped indoor venues
    indoorPicker: true, // shows the vertical floor level
    compassButton: true, // shows the compass (top/right) when bearing is non-zero
    myLocationEnabled: true,
    myLocationButton: true, // shows the default My location button
    region: { // Camera center of the map
        latitude: 37.368122,
        longitude: -121.913653,
        zoom: 10, // Zoom in points
        bearing: 45, // orientation measured in degrees clockwise from north
        viewingAngle: 30 // measured in degrees
    }
});

var annotation1 = maps.createAnnotation({
    latitude: 37.368122,
    longitude: -121.913653,
    title : "titleHere",
    subtitle : "subtitleHere"
});

mapView.addAnnotation(annotation1);
$.index.add(mapView);

$.index.open();
```

**Here is the trace output**
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGBitmapContextGetData: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Cannot find image dav_one_way_16_256
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Invalid texture state for dav_one_way_16_256.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Cannot find image polyline_colors_texture
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Invalid texture state for routesTextureState.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Cannot find image polyline_colors_texture_dim
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.
[DEBUG] :  2016-10-07 00:45:08.348 googleMapsTest[57615:249656] ((null)) was false: Invalid texture state for routesDimTextureState.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextGetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetCompositeOperation: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextGetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextGetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  Oct  7 00:45:08  googleMapsTest[57615] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Cannot find image GMSSprites-0-2x
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Cannot find image GMSNavSprites-0-2x
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Cannot find image GMSNavNightModeSprites-0-2x
[DEBUG] :  2016-10-07 00:45:08.374 googleMapsTest[57615:249656] ((null)) was false: Image data can't be NULL.

**Comment by yozef** [comment]
Same here, though not seeing the output logs you have pasted (I see no traceouts), the App just crashes in Simulator.

**Comment by cansoysal** [comment]
@yozef I only set debug level to trace

**Comment by hansemannn** [comment]
Could be fixed by using the new Google Maps iOS SDK 2.1.0, please try https://github.com/hansemannn/ti.googlemaps/pull/51

**Comment by cansoysal** [comment]
Unfortunately 2.1.0 made no difference, it keep crashing :/

**Comment by yozef** [comment]
as well as 2.6.0 :(

**Comment by hansemannn** [comment]
This is not reproducible using [2.6.0 B2](https://github.com/hansemannn/ti.googlemaps/releases/tag/v2.6.0-beta.2), @yozef confirmed yesterday.
