### ISSUE TITLE
annotation.updateLocation not working

### ISSUE THREAD

**Issue by bitfabrikken** [hansemannn/ti.googlemaps#62]
The follow example should move the annotation after 5 seconds - it doesn't :)

(sorry can't get code tags to work this time)

var win = Ti.UI.createWindow({});
win.open();

var maps = require("ti.googlemaps");
maps.setAPIKey("<YOUR_GOOGLE_MAPS_API_KEY>");

var mapView = maps.createView({
    mapType: maps.MAP_TYPE_TERRAIN,
    indoorEnabled: true,
    indoorPicker: false,
    compassButton: true,
    myLocationButton: true,
    myLocationEnabled: true,
    region: {
        latitude: 37.368122,
        longitude: -121.913653,
        zoom: 0
    }
});
win.add(mapView);

var annotation = maps.createAnnotation({
    latitude: 37.368122,
    longitude: -121.913653,
    title: "drag me",
    subtitle: "please drag me",
    draggable: true
});

mapView.addAnnotation(annotation);

setTimeout(function(){
    Ti.API.warn("moving annotation to -50, 50!");
    annotation.updateLocation({latitude: -50, longitude: 50 });
},5000);

**Comment by yozef** [comment]
I had this same issue. I think it's the way the new addAnnotation works.

What I have done is removed the annotation, and re-added it.

example:

var myAnn = maps.createAnnotation({ ...});

mapView.addAnnotation(myAnn);

setTimeout(function(){
  mapView.removeAnnotation(myAnn); // remove it
  myAnn = maps.createAnnotation({ ...}); // recreate it
  mapView.addAnnotation(myAnn); // re-add it
},5000);

It know it's not the ideal solution.

**Comment by hansemannn** [comment]
@yozef You added the `updateLocation` API, maybe it has kroll-/ main-thread issues? @bitfabrikken which thread are you running on?

**Comment by bitfabrikken** [comment]
@hansemannn how can I see that?

**Comment by hansemannn** [comment]
If you have the `run-on-main-thread` property in your tiapp.xml, you're running on main-thread, otherwise on kroll-thread. I'm usually testing with main-thread.

**Comment by bitfabrikken** [comment]
@hansemann, @yozef: Ok I must be running on kroll-thread then, as I have no run-on-main-thread in tiapp.xml - not for my app, nor for tishadow

**Comment by hansemannn** [comment]
Bonus tip: Try to upgrade sooner than later and report possible issues to the Titanium JIRA. We are currently actively fixing outstanding issues and will likely make it the default in a few versions. So the more people test it already, the more feedback we get for possible use-cases we didn't catch so far :-)

**Comment by hansemannn** [comment]
`<property name="run-on-main-thread" type="bool">true</property>` in your tiapp.xml toplevel, that's it!

**Comment by yozef** [comment]
It's causing issues for me too with run-on-main-thread. I'll take your advice and check it out this weekend.

**Comment by hansemannn** [comment]
Huii, fixed it!

**Comment by yozef** [comment]
I was working on it yesterday, trying to figure out the issue...

**Comment by hansemannn** [comment]
@yozef Basically, the issue was in the first line, where the arguments have been passed incorrectly to the main-thread. Replaced that line and added the (optional) animation properties.
