### ISSUE TITLE
Users location icon looks weird

### ISSUE THREAD

**Issue by bitfabrikken** [hansemannn/ti.googlemaps#65]
This is in simulator - is it supposed to look like this?

![simulator screen shot 12 jan 2017 11 41 15](https://cloud.githubusercontent.com/assets/2039652/21886475/270ec0dc-d8bc-11e6-80f4-422e90935271.png)

**Comment by hansemannn** [comment]
Yeah, wondered the same. I think it's a regression in the latest GoogleMaps iOS SDK. Pretty sure they fixed it already, let me update the SDK later today.

**Comment by yozef** [comment]
No this is Normal for GoogleMaps iOS SDK, and this will show like that ONLY on the Simulator. When you run it on the device, it's normal without the white square :)

**Comment by bitfabrikken** [comment]
Thanks @yosef, that's good to know :)
