### ISSUE TITLE
getMarker when clusteritemclick

### ISSUE THREAD

**Issue by usamecavga** [hansemannn/ti.googlemaps#82]
Hi,

I need to getMarker for change marker icon in cluster with clusteritemclick event. I get mapView but not clicked marker. Can you help me?

Best,
Usame

**Comment by hansemannn** [comment]
Cluster items are abstracted structured that do not have an instance behind it - to keep the clusters flexible and performant. You can identify the marker behind it by useing the `userData` property to store user-related data like the item ID. Properties returned:

- latitude
- longitude
- title
- subtitle
- userData

There are no plans to change this behavior.
