### ISSUE TITLE
Map Pin Colors

### ISSUE THREAD

**Issue by burgons** [hansemannn/Ti.GoogleMaps#9]
Nice Module!

Is there a method to change the map pin colours?

Cheers

**Comment by yozef** [comment]
var marker = maps.createMarker({
      icon: "pin.png", // <---- here you can use your own pin image
});

**Comment by burgons** [comment]
Thanks yozef

I spotted that "icon" property at about the same time that you posted your reply!

Do you know if there is a programmatic way of activating a particular pin's annotation?

Cheers

**Comment by yozef** [comment]
Hi Burgons, what do you mean by activating? (adding it to the map?)

**Comment by burgons** [comment]
To show the info window (or annotation) associated with the map pin. So that I can highlight a particular one.

**Comment by burgons** [comment]
OK, I've found that you can identify a single Pin if you give it a custom attribute "id: 1" upon creation, like this:
        var marker = Alloy.Globals.googleMap.createMarker({
            latitude: location.latitude,
            longitude: location.longitude,
            title: location.title,
            snippet: location.city,
            id: 1,
            icon: "images/imagefiles_location_map_pin_pink6.png"
        });

I can then retrieve that info as follows:

mapView.addEventListener("markerclick", handlerMarkerClickEvent);
function handlerMarkerClickEvent(e) {
    Ti.API.info("\"markerclick\" event fired!");
    Ti.API.info("source: " +JSON.stringify(e.source));
}

and here's my console output, where I can see the "annotation.id = 1":

{
	"horizontalWrap": true,
	"visible": true,
	"mapType": 3,
	"camera": {
		"zoom": 10,
		"longitude": -1.613172,
		"latitude": 54.980541
	},
	"annotation": {
		"id": 1
	}
}

**Comment by yozef** [comment]
After adding the annotation on the map, the user can tap the annotation to show the infoWindow (these can be set with these params of the createMarker, title : "Appcelerator, Inc" and snippet : "1732 N. 1st Street, San Jose". However I think you would like to programatically display the infoWindow?

**Comment by burgons** [comment]
Yes that would be my plan...

**Comment by yozef** [comment]
oh I see. Ok :)

**Comment by yozef** [comment]
I am not sure if `selectedMarker` was implemented, however this is the method you're looking for to programatically display the infoWindow.

**Comment by burgons** [comment]
I can't find a way to activate the `selectedMarker `.

Anyway, I think I spoke too soon. For some reason I can't now retrieve the pin ID. It's not appearing in the object any longer.
Any ideas?

**Comment by hansemannn** [comment]
hey @burgons & @yozef, thanks for asking! I will update the module right now to support the following:
```
marker.icon = [GMSMarker markerImageWithColor:[UIColor blackColor]];
```
I will also expose the new property `selectedMarker`. Stay tuned!

**Comment by hansemannn** [comment]
New marker properties "image" for pin images and "pinColor" for pin tinting are now pushed. Please try the changes, I will release the version in the next weeks after I have some more time to test.

**Comment by hansemannn** [comment]
Closing this issue for now, please reopen if it does not work!

**Comment by burgons** [comment]
Thanks Hans

I'll give it a try and feed back. 

Cheers

**Comment by burgons** [comment]
Thanks Hans.

The previous update (to enable marker color) is working perfectly.

Much appreciated!
